### ISSUE TITLE
代码作用

### ISSUE THREAD

**Issue by caobochao-cs** [JacksonWuxs/taac2021-Video-Classification-Rank5#1]
您好，我是一名初学者，想学习下您的代码，但是很多代码文件作用不清楚，请问您可以提供一份更加详细的readme吗，万分感谢！

**Comment by JacksonWuxs** [comment]
抱歉，近期可能没有时间整理更详细的readme。不过您可以直接阅读源码，源码中的注释以及实现还是整体还是清晰的。希望能对你有帮助。
